### ISSUE TITLE
zip support

### ISSUE THREAD

**Issue by ivarflakstad** [qgisinspiretools/qgis-inspire-atom-client-plugin#5]
Just putting this in its own issue on behalf of @Maaka2890

> Hi Juergen,
> 
> Thank you for you plugin. It is very useful to us.
>
>The atom feed I use only offers .zip (with GML in it).
>When your plugin loads the zip into the layer panel it does not ask "Select vector layers to add..." (which Qgis normally does when dropping a .zip in). Only the first 'vector layer' is loaded. whereas some GML's have multiple layers in them.
>
>Would it be possible to change it so all the 'layers' will load? or the "select vector layer to add..." pops up?
>
>If you want I can send you the URL of the feed and more details.
>
>Thanks in advance,
>Maaka

**Comment by Maaka2890** [comment]
tested and works like a charm :)

**Comment by ejn** [comment]
Should now be fixed in the latest version for QGIS 3
