### ISSUE TITLE
Post-install issue

### ISSUE THREAD

**Issue by mlseguin** [qgisinspiretools/qgis-inspire-atom-client-plugin#9]
Hi, 
This plugin looks great but I can't make it work. I downloaded the ZIP file (qgis-inspire-atom-client-plugin-master.zip) and used the zip installation process in Qgis extension windows. The plugins fails to launch after installation with this message :

```
ModuleNotFoundError: No module named 'qgis-inspire-atom-client-plugin-master.resources' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/marie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-inspire-atom-client-plugin-master\__init__.py", line 24, in classFactory
    from .inspireatomclient import InspireAtomClient
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/marie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis-inspire-atom-client-plugin-master\inspireatomclient.py", line 29, in 
    from .resources import *
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'qgis-inspire-atom-client-plugin-master.resources'


Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.18.1-Zürich Zürich, 202f1bf7e5 

Chemin Python :
C:/OSGEO4~1/apps/qgis/./python
C:/Users/marie/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/marie/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/marie/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

Thanks for your time

**Comment by ejn** [comment]
Hi, just downloading a zip of the source and trying to load it into QGIS won't work - you need to compile (the python resources) first, usually with the [plugin-builder tool](http://g-sherman.github.io/plugin_build_tool/).

Unless you're developing on the plugin, this shouldn't be necessary: You can download and instal the plugin via the QGIS Plugin Manager as it is available in the standard QGIS Plugins Repository: https://plugins.qgis.org/plugins/inspireatomclient/. As it is still marked as experimental, then you will need to enable experimental plugins in the QGIS Plugin Manager before you see it (it's no longer very experimental, but you may experience performance problems with feeds containing large numbers of entries.

Alternatively you may download the Zip archive containing the compiled plugin from the QGIS Plugin Repository linked above and then install from the zipfile.
